language: c
install:
  - sudo apt-get update
  - sudo apt remove --purge --auto-remove cmake
  - CMAKE_URL="https://cmake.org/files/v3.20/cmake-3.20.0-linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version
  - sudo apt-get install -y --no-install-recommends valgrind

addons:
  apt:
    packages:
      - doxygen

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd FileSystem
  - valgrind --leak-check=yes --log-file=log.txt ./client_without_server < ../../tests/valgrind_test_commands
  - echo "Valgrind log:"
  - cat log.txt
  - python ../../tests/valgrind_parser.py
  - cd ..
  - cd ..

after_succes:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    all_branches: true