language: c
install:
  - sudo apt-get update
  - sudo apt remove --purge --auto-remove cmake
  - version=3.20
  - build=0
  - mkdir ~/temp
  - cd ~/temp
  - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
  - tar -xzvf cmake-$version.$build.tar.gz
  - cd cmake-$version.$build/
  - ./bootstrap
  - make -j$(nproc)
  - sudo make install
  - cmake --version
  - sudo apt-get install -y --no-install-recommends valgrind

addons:
  apt:
    packages:
      - doxygen

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd FileSystem
  - valgrind --leak-check=yes --log-file=log.txt ./client_without_server < ../../tests/valgrind_test_commands
  - echo "Valgrind log:"
  - cat log.txt
  - python ../../tests/valgrind_parser.py
  - cd ..
  - cd ..

after_succes:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    all_branches: true