language: c
install:
  - sudo apt-get update
  - sudo apt remove --purge --auto-remove cmake
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
  - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
  - sudo apt update
  - sudo apt install kitware-archive-keyring
  - sudo rm /etc/apt/trusted.gpg.d/kitware.gpg
  - sudo apt update
  - sudo apt install cmake
  - sudo apt-get install -y --no-install-recommends valgrind

addons:
  apt:
    packages:
      - doxygen

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd FileSystem
  - valgrind --leak-check=yes --log-file=log.txt ./client_without_server < ../../tests/valgrind_test_commands
  - echo "Valgrind log:"
  - cat log.txt
  - python ../../tests/valgrind_parser.py
  - cd ..
  - cd ..

after_succes:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    all_branches: true